config/routes.rb
Rails.application.routes.draw do

  devise_for :owners
  devise_for :users
  root 'landing#index'

  resources :shops do
    resources :offers, :except => [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base

  self.abstract_class = true
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :shop

  validates :name, :presence => true

  validates :savings, :presence => true

  validates :validity, :presence => true
end

app/models/owner.rb
class Owner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  has_many :offers
  

  validates :name, :presence => true
  validates :address, :presence => true
  validates :area, :presence => true
  validates :description, :presence => true
  validates :picture, :presence => true
  validates :opening_hours, :presence => true
  validates :location, :presence => true
  validates :website, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery prepend: true

  def after_sign_in_path_for(users)
    shops_path
  end

  def after_sign_in_path_for(owners)
    shops_path
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    

  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @shop = Shop.find(params[:shop_id])
    @offer = @shop.offers.new
  end

  def create
    @shop = Shop.find(params[:shop_id])
    @offer = @shop.offers.new(offer_params)

    if @offer.save
      redirect_to shop_path(@offer.shop)
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:shop_id])
    @offer = Offer.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:shop_id])
    @offer = Offer.find(params[:id])

    if @offer.update(offer_params)
      redirect_to shop_path(@offer.shop)
    else
      render :edit
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to shop_path(@offer.shop)
  end


  private
    def offer_params
      params.require(:offer).permit(:name, :savings, :validity)
    end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @shops = Shop.all
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      flash[:notice] = "Shop successfully added!"
      redirect_to shops_path(@shop)
    else
      render :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    flash[:notice] = "The shop has been deleted"
    redirect_to shops_path
  end

  private
    def shop_params
      params.require(:shop).permit(:name, :address, :area, :description, :picture, :opening_hours, :location, :website )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/landing/index.html.erb
<div class="container">

  <h1>Welcome to strolls</h1>
  <p>Discover the hidden gems in your city through deals</p>

  <h3>Who are you?</h3>

  <hr>

  <div class="col-xs-6">
    <a href="users/sign_up">
    <h4>I'm a new client</h4>
    <p>I want to discover</p>
    </a>

    <a href="users/sign_in">
    <h4>I'm already a client</h4>
    <p>I want to discover</p>
    </a>
  </div>

  <div class="col-xs-6">
    <a href="owners/sign_up">
    <h4>I'm a new shop owner</h4>
    <p>I want to make great deals available</p>
    </a>

    <a href="owners/sign_in">
    <h4>I'm already have a shop on strolls</h4>
    <p>I want to discover</p>
    </a>
  </div>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix there errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>


  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Strolls</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><%= link_to 'Logout', destroy_user_session_path, method: :delete %><span class="sr-only">(current)</span></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <%= flash[:alert] %>
    <%= flash[:notice] %>


    <div class="container">
    <!-- Main component for a primary marketing message or call to action -->
      <div class="jumbotron">
        <%= yield %>
      </div>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>


  </body>
</html>

app/views/offers/_form.html.erb
<div class="container">

  <%= render('layouts/errors', :object => @offer) %>

    <%= form_for [@shop, @offer] do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :savings %>
      <%= f.number_field :savings, class: 'form-control' %>

      <%= f.label :validity %>
      <%= f.date_field :validity, class: 'form-control' %>

      <p><%= f.submit 'Launch this offer on Strolls', class: 'btn btn-lg btn-primary btn-block'%></p>
    <% end %>
</div>

app/views/offers/edit.html.erb
<% content_for(:title, "Edit Offer | Strolls") %>

<h1>Edit Offer</h1>

<%= render "form" %>

app/views/offers/new.html.erb
<% content_for(:title, "New Offer | Strolls") %>

<h1>New offer for <%= @shop.name %></h1>

  <%= render 'form' %>

app/views/owners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/shops/_form.html.erb
<div class="container">

  <%= render "layouts/errors", :object => @shop %>

  <%= form_for @shop do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>

    <%= f.label :area %>
    <%= f.text_field :area, class: 'form-control' %>

    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.label :picture %>
    <%= f.text_field :picture, class: 'form-control' %>

    <%= f.label :opening_hours %>
    <%= f.text_field :opening_hours, class: 'form-control' %>

    <%= f.label :location %>
    <%= f.text_field :location, class: 'form-control' %>

    <%= f.label :website %>
    <%= f.text_field :website, class: 'form-control' %>

    <%= f.submit 'Add this shop on Strolls', class: 'btn btn-lg btn-primary btn-block'%>
  <% end %>

</div>

app/views/shops/edit.html.erb
<% content_for(:title, "Edit Shop | Strolls") %>

<h1>Edit Shop</h1>

<%= render "form" %>

<hr>
<%=  link_to "Return to Shops", shops_path %>

app/views/shops/index.html.erb
<% content_for(:title, "Shop | Strolls") %>
<h1>Shops</h1>

<ul>
  <% @shops.each do |shop| %>
    <li><%= link_to shop.name, shop_path(shop) %></li>
  <% end %>
</ul>

<hr>

<%=  link_to "New Shop", new_shop_path %>

app/views/shops/myshop.html.erb
<div class="container">
  <h1>Manage your shop page</h1>

  <p>Register a new shop to Strolls</p>

  <%=  link_to "New Shop", new_shop_path %>

</div>

app/views/shops/new.html.erb
<% content_for(:title, "New Shop | Strolls") %>

<h1>New Shop</h1>


<%= render "form" %>

<%=  link_to "Return to Shops", shops_path %>

app/views/shops/show.html.erb
<% content_for(:title, "Shop | Strolls") %>

<h1><%= @shop.name %></h1>

<div class="container">
  <div class="col-xs-3">
      <%= @shop.description %>
  </div>

  <div class="col-xs-3">
    <%= @shop.address %>
  </div>

  <div class="col-xs-3">
    <%= image_tag  @shop.picture, class: 'img-circle'%>
  </div>
</div>

<div class="container">


  <% if @shop.offers.any? %>
    <h4>Here are the offers for this shop:</h4>

    <ul>
      <% @shop.offers.each do |offer| %>
        <li>
          <%= offer.name %> |
          estimate savings: <%= offer.savings %> |
          valid until: <%= offer.validity %>
          <%= link_to "Edit", edit_shop_offer_path(@shop, offer) %> |
          <%= link_to "Delete", shop_offer_path(@shop, offer),
            :data => {:confirm => "Are you sure?",
            :method => "delete"} %>
        </li>
      <% end %>
    </ul>
  <% else %>
    <p>There are no offers yet!</p>
  <% end %>

  <p><%= link_to "Add an offer", new_shop_offer_path(@shop) %></p>
  <p><%= link_to "Delete Shop", shop_path(@shop),
            :data => {:confirm => "Are you sure?",
            :method => "delete"} %></p>


  <p><%= link_to "Return to shops", shops_path %></p>
</div>